print('Hei, la oss prøve en liten sjakk-quiz!')
print()
print('1. Vi har sluttspillet ♔ ♗ ♘ mot ♚.')
print('Hva blir dette med korrekt spill fra begge parter?')
print('A. Seier til hvit, B. Remis, C. Seier til svart?')
svar = input('Ditt svar: ')
print('Korrekt var A. Du svarte', svar)
print()
print('2. Hva kalles åpningen \u2659e4 - \u265Fc5')
print('A. Carlsen-gambit, B. Siciliansk, C. Russisk?')
svar = input('Ditt svar: ')
print("Korrekt var B. Du svarte", svar)
print()
print('Hvor mange brikker er det i sjakk?')
print('A:22, B:32, C:28')
svar = input('Ditt svar: ')
print('Ritig svar var B. Du svarte',svar)
print()
print('Hvilken brikke er det viktigst å beskytte?')
print('A:Kongen, B:dronningen, C:løperen')
svar = input('Ditt svar: ' )
print('Riktig svar var A, du svarte', svar)
print()
print('Hvem er nåværende verdensmester i sjakk?')
print('A:Caruna, B:Marty, C:Carlsen')
svar = input('Ditt svar: ')
print('Riktig svar var C, du svarte',svar)
